language: node_js
node_js:
  - "8"
before_install:
  - echo 'installing dependencies'
  - sudo apt-get install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++
install:
  - echo 'installing npm packages'
  - npm install
script:
  - npm run prebuild
  - npm run test
  - npm run lint
  - npm run generate:gh-pages
