language: node_js
node_js:
  - "8"
before_install:
  - echo 'installing dependencies'
  - sudo apt-get install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++
install:
  - echo 'installing npm packages'
  - npm install
script:
  - npm run prebuild
  - npm run test
  - npm run lint
  - npm run gh-pages:generate
# staging environment in datocms
notifications:
  webhooks:
  - https://webhooks.datocms.com/85346aa7eb904faa0ea9/deploy-results
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local-dir: dist
  keep-history: true
  on:
    branch: master
