language: node_js
node_js:
  - "8"
before-install:
  sudo apt-get install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++

script:
  npm run test
  npm run lint
  npm run generate:gh-pages
