language: node_js
node_js:
  - "8"
before_install:
  - echo 'installing dependencies'
  - sudo apt-get install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++
install:
  - echo 'installing npm packages'
  - npm install
script:
  # while the dev server is starting we do the rest of the work
  - npm run build
  - npm run test
  - npm run lint
  - npm run generate
notifications:
  webhooks:
  # staging environment in datocms
  - https://webhooks.datocms.com/85346aa7eb904faa0ea9/deploy-results
  # production environment in datocms
  - https://webhooks.datocms.com/c528c7e6c500371acb88/deploy-results
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_API_KEY  # Set in travis-ci.org dashboard, marked secure
  local-dir: dist
  keep-history: true
  on:
    branch: master
    condition: $DEPLOY_ENV=GH_PAGES
deploy:
  provider: surge
  project: ./dist/
  domain: www.worldwateratlas.org
  on:
    branch: master
    condition: $DEPLOY_ENV=SURGE
