[build]
  command = "npm run lint -- --max-warnings 0 && npm run build && npm run generate"
  publish = "dist/"
  functions = "functions"
  [build.environment]
    NODE_VERSION = "12"
    NODE_ENV = "development"
    NPM_CONFIG_AUDIT = "false"
    NPM_CONFIG_PRODUCTION = "false"
  [build.processing]
    skip_processing = true

[dev]
  framework = "#custom"
  command = "npm run dev"
  publish = "/"
  port = 3001
  targetPort = 3000
  autoLaunch = false

[context.production.environment]
  NODE_ENV = "production"
  AWS_LAMBDA_JS_RUNTIME = "nodejs12.x"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    cache-control = '''
      public,
      max-age=31536000,
      immutable'''
